<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>HMWK</string>
   </array>
  <key>name</key>
  <string>HOMEWORK</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.HOMEWORK</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.HOMEWORK</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.HOMEWORK</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(;)</string>
          <key>name</key>
          <string>punctuation.HOMEWORK</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#var</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#neg</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.HOMEWORK</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.HOMEWORK</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.HOMEWORK</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\=\=)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.HOMEWORK</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\=\=)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.HOMEWORK</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&gt;&gt;)([\x{0020}])(.*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.HOMEWORK</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>comment.HOMEWORK</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>comment.HOMEWORK</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>exp</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.HOMEWORK</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#exp__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.HOMEWORK</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>exp__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#neg</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#var</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#punc</string>
        </dict>
       </array>
    </dict>
    <key>keys</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([iI]f|[wWtT]hen|[hH]ow|[wW]hy|[wW]ho|[wW]hat|[oO]nce)</string>
          <key>name</key>
          <string>keyword.HOMEWORK</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#keys</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#neg</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#punc</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#exp</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#var</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\W]{2,})</string>
          <key>name</key>
          <string>text.HOMEWORK</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\S]+)</string>
          <key>name</key>
          <string>text.HOMEWORK</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\[\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.HOMEWORK</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.HOMEWORK</string>
          <key>end</key>
          <string>(\[\[)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.HOMEWORK</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>neg</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\-\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.HOMEWORK</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b)(\d+)(\.)(\d+)</string>
          <key>name</key>
          <string>constant.numeric.HOMEWORK</string>
        </dict>
       </array>
    </dict>
    <key>punc</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([\.\?\+\=\-\x{002c}\&amp;\!\:\;])</string>
          <key>name</key>
          <string>punctuation.HOMEWORK</string>
        </dict>
       </array>
    </dict>
    <key>var</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([xXyYzZ]{1,3})</string>
          <key>name</key>
          <string>var.HOMEWORK</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
